In [6]:
# Import required modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import boxcox
from statsmodels.tsa.stattools import adfuller, acf, pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [7]:
# Set plot parameter
plt.rcParams['figure.figsize'] = (10, 7.5)

In [8]:
# Read data file
url = 'https://raw.githubusercontent.com/faadeola/oil_prices_ts_analysis/refs/heads/main/oil_prices_2426.csv'
oil = pd.read_csv(url, parse_dates = True)

In [9]:
# display sample of data
oil.sample(10)

           date  price (dollars)
304  22/07/2025            97.79
6    27/09/2024            34.08
315  02/08/2025           108.59
381  07/10/2025           118.83
242  21/05/2025            64.21
283  01/07/2025            85.55
69   29/11/2024            30.81
124  23/01/2025            17.75
293  11/07/2025            95.59
402  28/10/2025           123.72

In [15]:
# Display shape of the data
print(f'The oil data consist of {oil.shape[0]} rows and {oil.shape[1]} columns')

The oil data consist of 500 rows and 2 columns

In [18]:
# Display summary statistics of the data
oil.describe().round(2)

       price (dollars)
count           500.00
mean             75.87
std              42.91
min              16.48
25%              35.37
50%              64.29
75%             111.57
max             158.78