In [72]:
# Import required modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import boxcox
from statsmodels.tsa.stattools import adfuller, acf, pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [73]:
# Set plot parameter
plt.rcParams['figure.figsize'] = (10, 7.5)

In [74]:
# Read data file
url = 'https://raw.githubusercontent.com/faadeola/oil_prices_ts_analysis/refs/heads/main/oil_prices_2426.csv'
oil = pd.read_csv(url, parse_dates=['date'], dayfirst=True)

In [75]:
# display sample of data
oil.sample(10)

          date  price (dollars)
44  2024-11-04            36.60
21  2024-10-12            41.15
140 2025-02-08            27.16
413 2025-11-08           133.36
188 2025-03-28            51.76
469 2026-01-03           131.39
312 2025-07-30           108.50
330 2025-08-17           109.97
296 2025-07-14            98.50
314 2025-08-01           107.96

In [76]:
# Display shape of the data
print(f'The oil data consist of {oil.shape[0]} rows and {oil.shape[1]} columns')

The oil data consist of 500 rows and 2 columns

In [77]:
# Display summary statistics of the data
oil.describe().round(2)

                      date  price (dollars)
count                  500           500.00
mean   2025-05-28 12:00:00            75.87
min    2024-09-21 00:00:00            16.48
25%    2025-01-23 18:00:00            35.37
50%    2025-05-28 12:00:00            64.29
75%    2025-09-30 06:00:00           111.57
max    2026-02-02 00:00:00           158.78
std                    NaN            42.91

In [78]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             500 non-null    datetime64[ns]
 1   price (dollars)  500 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 7.9 KB

In [79]:
# set date as the index column
oil = oil.set_index('date')